version: '3.3'

services:
  be_180197_presta:
    image: cinekdbw/lamper
    ports:
      - 18019:80
      - 18020:443
    restart: always
    environment:
      DB_SERVER: actina15.maas
      DB_USER: be_180197
      DB_PASSWD: lamper123
      DB_NAME: be_180197_db
      PS_FOLDER_ADMIN: admin123
      PS_DEV_MODE: 0
      ALLOW_OVERRIDE: 1
      PS_INSTALL_AUTO: 0
    deploy:
      replicas: 1