version: '3.3'

services:
  my-sql:
    image: mysql:5.7
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
    volumes:
      - db:/var/lib/mysql
      - ./config/dump.sql:/docker-entrypoint-initdb.d/setup.sql
  prestashop:
    depends_on:
      - my-sql
    image: 5965773c828a #tutaj trzeba zmienic id image
    ports:
      - 8080:80
      - 443:443
    restart: always
    environment:
      DB_SERVER: my-sql
      DB_USER: root
      DB_PASSWD: root
      DB_NAME: lamper
      PS_FOLDER_ADMIN: admin123
    volumes:
      - prestashop:/var/www/html
volumes:
  prestashop:
  db: