<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2nmprbe\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2nmprbe/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2nmprbe.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2nmprbe\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2nmprbe\appProdProjectContainer([
    'container.build_hash' => '2nmprbe',
    'container.build_id' => '034fd71b',
    'container.build_time' => 1636793049,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2nmprbe');
