<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBzw6jgo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBzw6jgo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBzw6jgo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBzw6jgo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBzw6jgo\appDevDebugProjectContainer([
    'container.build_hash' => 'Bzw6jgo',
    'container.build_id' => '0ddb6d73',
    'container.build_time' => 1636800455,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBzw6jgo');
